FORMAT: 1A
HOST: https://auth.kneu.edu.ua/api/

# KNEU OAuth 2.0 and RESTful API

Документація з використання веб-сервісів КНЕУ:
 * Протокол OAuth 2.0 - забезпечує єдиний інтерфейс авторизації користувачів на веб-ресурсах КНЕУ (через веб-сайт університету).
 * RESTful API - надає інформацію для інших програмних продуктів КНЕУ стосовно структури університету: факультети, кафедри, викладачі, спеціальності, студенти, користувачі.

Для полегшення реалізації інтеграції із веб-сервісами було розроблено наступні додатки:
 * [PHP client for KNEU RESTful API Service](https://github.com/berejant/kneu-api) - PHP-бібліотека для роботи з КНЕУ RESTful API та OAuth 2.0. Документація до бібліотеки розміщена в файлі README.md в Github-репозиторії.
 * [JS client for KNEU RESTful API Service](https://www.npmjs.com/package/kneu-api-client) - JS-бібліотека для роботи з КНЕУ RESTful API та OAuth 2.0. Документація до бібліотеки розміщена в файлі README.md в Github-репозиторії.
 * [KNEU Laravel Socialite](https://github.com/berejant/kneu-laravel-socialite-provider) - пакет, який реалізує авторизацію через сервер КНЕУ в Laravel-додатках.

# OAuth 2.0
Існує два типи авторизації:
 * авторизація клієнта (користувача) через браузер. Дозволяє ідентифікувати конкретного користувача КНЕУ: студента, викладача, співробітника тощо.
 * авторизація сервера стороннього додатку. Дозволяє отримати доступ до RESTful API без прив'язки до конкретного користувача.

В обох випадках процедура авторизації закінчується отриманням `access_token` для доступу до RESTful API.

Для роботи з OAuth 2.0 необхідно отримати для свого програмного додатку наступні реквізити доступу:
 * **client_id** - `integer` - ідентифікатор стороннього додатку (може передаватися публічно)
 * **client_secret** - `char(32)` - секретний код стороннього додатку для ідентифікації (має зберігатися в таємниці)

Вказані вище реквізити доступу надаються [Відділом мережевих технології Центру автоматизації управління університетом](https://kneu.edu.ua/ua/University_en/control_center/center_ayy/support_www/). Для цього необхідно звернутися до Відділу особисто або надіслати письмово вмотивовану заяву на отримання доступу. В заявці обов'язково необхідно вказати назву та призначення інформаційної системи та доменні імена.

## Авторизація клієнта

Складається з чотирьох кроків:

 1. Для початку процесу авторизації клієнта необхідно направити за адресою:
    > http://auth.kneu.edu.ua/oauth?`response_type`=code&`client_id`={CLIENT_ID}&`redirect_uri`={REDIRECT_URI}&`state`={STATE}

    де:
     * `response_type` - `string` – тип відповіді, яку отримує сторонній ресурс. Доступне лише одне значення: **code**.
     * `client_id` - `integer`  – ідентифікатор стороннього додатку.
     * `redirect_uri` – `string` - адреса, на яку буде передано параметр `code`. Ця адреса повинна буде знаходиться **в межах домену**, вказаного при реєстрації стороннього ресурсу.
     * `state` – `string` - optional. Якщо вказано – значення цього параметру буде передано у `redirect_uri`.
 2. Користувачу буде запропоновано вести його логін та пароль.
 У випадку, якщо користувач раніше вже пройшов авторизацію на веб-сайті КНЕУ – його буде одразу переадресовано на `redirect_uri` без будь-яких затримок та додаткових діалогів.
 Також, замість логіну та паролю, користувач може використати аккаунт в сторонньому сервісі або соціальній мережі (Google, Yandex, Facebook, Вконтакте, Mailru, Twitter тощо).
 3. Після успішної авторизації браузер користувача буде переадресовано за адресою `redirect_uri`, вказаної при відкритті діалогу. При цьому, для отримання доступу в GET-параметрах буде передано параметр code:
    > `redirect_uri`?`code`={code}[&`scope`={scope}]

    де:
    * `code` - `string` - спеціальний код для отримання `access_token`. Може бути використано протягом двох хвилин.
    * `scope` - `string` - optional. значення параметра scope, яке було передано на кроці 1.
 4. Отримання access_token. Для цього необхідно здійснити POST запит за адресою
    > https://auth.kneu.edu.ua/oauth/token

    Headers:
    - Content-Type: application/x-www-form-urlencoded

    POST-параметри:
     * `client_id` - `integer` - ідентифікатор стороннього додатку;
     * `client_secret` - `string` - секретний код стороннього додатку;
     * `grant_type` - `string` - вказати значення "**authorization_code**";
     * `code` - `string` - Код, який був переданий на `redirect_uri`;
     * `redirect_uri` - `string` - безпосередньо адреса `redirect_uri`, на який було здійсненно переадресацію клієнта.

    Відповідь міститиме JSON:
    ```json
    {
      "access_token": "96931eb1ed29a47b4c38f97f7d49a8f6",
      "token_type": "Bearer",
      "expires_in": 7200,
      "user_id": 999
    }
    ```
    Значення параметру `access_token` потрібно буде використати для роботи з RESTful API.

    В PHP-бібліотеці цей крок автоматизується за допомогою методу [**\Kneu\Api::oauthToken()**](https://github.com/berejant/kneu-api#oauthtokenclient_id-client_secret-code-redirect_uri)

## Авторизація сервера
Для авторизації серверу стороннього додатку необхідно здійснити POST-запит за адресою
> https://auth.kneu.edu.ua/oauth/token

Headers:
- Content-Type: application/x-www-form-urlencoded

POST-параметри:
 * `client_id` - `integer` - ідентифікатор стороннього додатку;
 * `client_secret` - `string` - секретний код стороннього додатку;
 * `grant_type` - `string` - вказати значення "**client_credentials**".

Відповідь міститиме JSON:
```json
{
  "access_token": "96931eb1ed29a47b4c38f97f7d49a8f6",
  "token_type": "Bearer",
  "expires_in": 7200,
}
```
Значення параметру `access_token` потрібно буде використати для роботи з RESTful API.

В PHP-бібліотеці цей крок автоматизується за допомогою методу [**\Kneu\Api::serverToken()**](https://github.com/berejant/kneu-api#servertokenclient_id-client_secret)

## Міжсайтовий вихід із системи
Після завершення сесії користувача в сторонньому додатку (дія "logout", "вихід") необхідно викликати процедуру завершення сесії на стороні сайту КНЕУ. Це допоможе уникнути конфлікту: коли користувач продовжує бути авторизованим на сайті КНЕУ, в той час в сторонньому додатку - вже вийшов із системи.
Для завершення сесії на стороні веб-сайту КНЕУ користувача необхідно направити за адресою:
> https://auth.kneu.edu.ua/oauth/logout?`client_id`={CLIENT_ID}&`redirect_uri`={REDIRECT_URI}

де:
 * `client_id` - `integer`  – ідентифікатор стороннього додатку.
 * `redirect_uri` – `string` - optional. Адреса, на яку буде переадресовано користувача після виходу із системи. Ця адреса повинна буде знаходиться **в межах домену**, вказаного при реєстрації стороннього ресурсу. Якщо не вказано - користувача буде на направлено на головну сторінку сайту КНЕУ.

Після переходу користувач буде вважатися таким, що вийшов із сайту КНЕУ. Це дозволить авторизуватися іншому користувачу.

# KNEU RESTful API
Для роботи з RESTful API необхідно володіти значенням `access_token`.
Запити здійснюються методом GET за адресами:
 * https://auth.kneu.edu.ua/api/[назва_сутності] - для отримання масиву наявних об'єктів вказаної сутності (Action list)
 * https://auth.kneu.edu.ua/api/[назва_сутності]/[id] - для отримання конкретного об'єкта зі вказаним id  вказаної сутності (Action item)

При виконанні запитів до RESTful API у заголовках необхідно передавати значення `access_token`:
> Authorization: Bearer [access_token]

Для спрощення роботи з API рекомендуєтся використати [PHP-бібліотеку](https://github.com/berejant/kneu-api) - готовий кліент для роботи з KNEU RESTful API.

## Факультети [/faculty]

### List - перелік факультетів [GET /faculty{?offset,limit}]
Дозволяє отримати перелік всіх факультетів


+ Parameters
    + offset (number, optional) - зсув вибірки від початку. Аналог SQL LIMIT [offset], [limit];
        + Default: 0
    + limit (number, optional) - кількість об'єктів у видачі (MAX = 2000). Аналог SQL LIMIT [offset], [limit];
        + Default: 500

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 206 (application/json)
    + Headers

            Content-Range: items [startIndex]-[endIndex]/[totalCount]

    + Body

            [
                {
                    "id": 1,
                    "name": "Економіки та управління"
                },
                ...
            ]


### Item - факультет [GET /faculty/{faculty_id}]
Дозволяє отримати інформацію про факультет за його ідентифікатором

+ Parameters
    + faculty_id (number, required) - Ідентифікатор факультету

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "name": "Економіки та управління"
            }


## Кафедри [/department]

### List - перелік кафедр [GET /department{?faculty_id,offset,limit}]
Дозволяє отримати перелік кафедр. Надає перелік:
 - всіх кафедр відсортованних за id.
 - кафедр вибраного факультету `faculty_id` відсортованних за назвою.

Об'єкт Кафедра надається разом з даними по зв'язанному об'єкту Факультет.


+ Parameters
    + faculty_id (number, optional) - Ідентифікатор факультету для вибірки кафедр певного факультету
    + offset (number, optional) - зсув вибірки від початку. Аналог SQL LIMIT [offset], [limit];
        + Default: 0
    + limit (number, optional) - кількість об'єктів у видачі (MAX = 2000). Аналог SQL LIMIT [offset], [limit];
        + Default: 500

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 206 (application/json)
    + Headers

            Content-Range: items [startIndex]-[endIndex]/[totalCount]

    + Body

            [
                {
                    "id": 53,
                    "faculty_id": 3,
                    "name": "Адміністративного та фінансового права",
                    "faculty": {
                        "id": 3,
                        "name": "Юридичний інститут"
                    }
                },
                {
                    "id": 57,
                    "faculty_id": 3,
                    "name": "Іноземних мов юридичного інституту",
                    "faculty": {
                        "id": 3,
                        "name": "Юридичний інститут"
                    }
                },
                ...
            ]


### Item - кафедра [GET /department/{department_id}]
Дозволяє отримати інформацію про кафедру за її ідентифікатором.
Об'єкт Кафедра надається разом з даними по зв'язанному об'єкту Факультет.

+ Parameters
    + department_id (number, required) - Ідентифікатор кафедри

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Body

            {
                "id": 53,
                "faculty_id": 3,
                "name": "Адміністративного та фінансового права",
                "faculty": {
                    "id": 3,
                    "name": "Юридичний інститут"
                }
            }


## Викладачі [/teacher]

### List - перелік викладачів [GET /teacher{?department_id,faculty_id,offset,limit}]
Дозволяє отримати перелік викладачів. Надає перелік:
 - всіх викладачів відсортаванних за id.
 - викладачів певного факультету `faculty_id` або кафедри `department_id` в алфавітному порядку за прізвищем.
Об'єкт викладач надається разом даними зв'язаних об'єктів Кафедра та Користувач (User).
Увага! Обєкт User є необов'язковий. Може бути відсутній, якщо викладач ще не зар'єструвався на сайті.

+ Parameters
    + department_id (number, optional) - Ідентифікатор факультету для вибірки викладачів певної кафедри
    + faculty_id (number, optional) - Ідентифікатор факультету для вибірки викладачів певного факультету
    + offset (number, optional) - зсув вибірки від початку. Аналог SQL LIMIT [offset], [limit];
        + Default: 0
    + limit (number, optional) - кількість об'єктів у видачі (MAX = 2000). Аналог SQL LIMIT [offset], [limit];
        + Default: 500

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 206 (application/json)
    + Headers

            Content-Range: items [startIndex]-[endIndex]/[totalCount]

    + Body

            [
                {
                    "id": 1105,
                    "department_id": 21,
                    "name": "Іваненко Іван Іванович",
                    "first_name": "Іван",
                    "middle_name": "Іванович",
                    "last_name": "Іваненко",
                    "image_url": "https:\/\/kneu.edu.ua\/files\/teacher\/teacher_photo\/thumbnail_1113333.jpg",
                    "user": {
                        "id": 5019,
                        "login": "example@gmail.com"
                    },
                    "department": {
                        "id": 21,
                        "faculty_id": 3,
                        "name": "Цивільного та трудового права"
                    }
                },
                ...
            ]


### Item - викладач [GET /teacher/{teacher_id}]
Дозволяє отримати інформацію про викладача за його ідентифікатором.
Об'єкт викладач надається разом даними зв'язаних об'єктів Кафедра та Користувач (User).
Увага! Обєкт User є необов'язковий. Може бути відсутній, якщо викладач ще не зар'єструвався на сайті.


+ Parameters
    + teacher_id (number, required) - Ідентифікатор викладача

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Body

            {
                "id": 1105,
                "department_id": 21,
                "name": "Іваненко Іван Іванович",
                "first_name": "Іван",
                "middle_name": "Іванович",
                "last_name": "Іваненко",
                "image_url": "https:\/\/kneu.edu.ua\/files\/teacher\/teacher_photo\/thumbnail_1113333.jpg",
                "user": {
                    "id": 5019,
                    "login": "example@gmail.com"
                },
                "department": {
                    "id": 21,
                    "faculty_id": 3,
                    "name": "Цивільного та трудового права"
                }
            }


## Спеціальності [/specialty]

### List - перелік спеціальностей [GET /specialty{?faculty_id,offset,limit}]
Дозволяє отримати перелік спеціальностей. Надає перелік:
 - всіх спеціальностей сортованних за id
 - спеціальностей певного факультету `faculty_id` сортованних за назвою.

Надається разом із даними зв'язаного об'єкту Факультет.


+ Parameters
    + faculty_id (number, optional) - Ідентифікатор факультету для вибірки спеціальностей певного факультету
    + offset (number, optional) - зсув вибірки від початку. Аналог SQL LIMIT [offset], [limit];
        + Default: 0
    + limit (number, optional) - кількість об'єктів у видачі (MAX = 2000). Аналог SQL LIMIT [offset], [limit];
        + Default: 500

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Headers

            Content-Range: items [startIndex]-[endIndex]/[totalCount]

    + Body

            [
                 {
                    "id": 131,
                    "faculty_id": 9,
                    "code": "6701",
                    "name": "Безпепека інформаційних і комунікаційних систем",
                    "faculty": {
                        "id": 9,
                        "name": "Інститут інформаційних технологій в економіці"
                    }
                },
                {
                    "id": 173,
                    "faculty_id": 9,
                    "code": "6.051",
                    "name": "Економіка",
                    "faculty": {
                        "id": 9,
                        "name": "Інститут інформаційних технологій в економіці"
                    }
                },
                ...
            ]


### Item - спеціальність [GET /specialty/{specialty_id}]
Дозволяє отримати інформацію про спеціальність за її ідентифікатором.
Надається разом із даними зв'язаного об'єкту Факультет.

+ Parameters
    + specialty_id (number, required) - Ідентифікатор спеціальності

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "faculty_id": 9,
                "code": "6101",
                "name": "Комп’ютерні науки",
                "faculty": {
                    "id": 9,
                    "name": "Інститут інформаційних технологій в економіці"
                }
            }



## Академічна група [/group]

### List - перелік академічних груп [GET /group{?specialty_id,faculty_id,offset,limit}]
Дозволяє отримати перелік академічних груп. Надає перелік:
 - всіх академічних груп відсортованних за id;
 - академичніних груп певної спеціальності `specialty_id` або факультету `faculty_id` відсортованних за назвою спеціальності та назвою групи

Об'єкт група надається разом із зв'занним об'єктом спеціальність.

+ Parameters
    + specialty_id (number, optional) - Ідентифікатор спеціальності для вибірки академічних груп певної спеціальності
    + faculty_id (number, optional) - Ідентифікатор факультету для вибірки академічних груп певного факультету
    + offset (number, optional) - зсув вибірки від початку. Аналог SQL LIMIT [offset], [limit];
        + Default: 0
    + limit (number, optional) - кількість об'єктів у видачі (MAX = 2000). Аналог SQL LIMIT [offset], [limit];
        + Default: 500

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Headers

            Content-Range: items [startIndex]-[endIndex]/[totalCount]

    + Body

            [
                {
                    "id": 13293,
                    "specialty_id": 33,
                    "course": 2,
                    "name": "ПР.-201",
                    "specialty": {
                        "id": 33,
                        "faculty_id": 18,
                        "code": "7.03040101",
                        "name": "Правознавство"
                    }
                },
                {
                    "id": 13297,
                    "specialty_id": 36,
                    "course": 2,
                    "name": "ОА.-201",
                    "specialty": {
                        "id": 36,
                        "faculty_id": 18,
                        "code": "7.03050901",
                        "name": "Облік і аудит"
                    }
                }
                ...
            ]


### Item - академічна група [GET /group/{group_id}]
Дозволяє отримати інформацію про академічну групу за її ідентифікатором.
Об'єкт група надається разом із зв'занним об'єктом спеціальність.

+ Parameters
    + group_id (number, required) - Ідентифікатор академічної групи

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Body

            {
                "id": 13297,
                "specialty_id": 36,
                "course": 2,
                "name": "ОА.-201",
                "specialty": {
                    "id": 36,
                    "faculty_id": 18,
                    "code": "7.03050901",
                    "name": "Облік і аудит"
                }
            }



## Студент [/student]

### List - перелік студентів [GET /student{?group_id,offset,limit}]
Дозволяє отримати перелік студентів. Надає перелік:
 - всіх студентів, відсортованних за id
 - студентів певної академічної групи `group_id` підсортованих в алфавітному порядку за прізвищем

Якщо студент зарєстрованний на сайті, додатково до додається інформацію про звязанну сутність користувач (User).
Якщо студент не зарєстрованний на сайті - інформація про User відсутня у результаті.

+ Parameters
    + group_id (number, optional) - отримати перелік студентів вказанної групи в алфавітному порядку
    + offset (number, optional) - зсув вибірки від початку. Аналог SQL LIMIT [offset], [limit];
        + Default: 0
    + limit (number, optional) - кількість об'єктів у видачі (MAX = 2000). Аналог SQL LIMIT [offset], [limit];
        + Default: 500

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Headers

            Content-Range: items [startIndex]-[endIndex]/[totalCount]

    + Body

            [
                {
                  "id": 444,
                  "group_id": 123,
                  "gradebook_id": "999999",
                  "sex": "male|female",
                  "name": "Іваненко Павло Володимирович",
                  "first_name": "Павло",
                  "middle_name": "Володимирович",
                  "last_name": "Іваненко",
                  "birthdate": "1992-07-13",
                  "user": {
                     "id": 32664,
                     "login": "fesannazar@gmail.com"
                  }
                },
                ...
            ]


### Item - студент [GET /student/{group_id}]
Дозволяє отримати інформацію про студента за його ідентифікатором

+ Parameters
    + group_id (number, required) - Ідентифікатор академічної групи

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Body

            {
              "id": 444,
              "group_id": 123,
              "gradebook_id": "999999",
              "sex": "male|female",
              "name": "Іваненко Павло Володимирович",
              "first_name": "Павло",
              "middle_name": "Володимирович",
              "last_name": "Іваненко",
              "birthdate": "1992-07-13",
              "user": {
                 "id": 32664,
                 "login": "fesannazar@gmail.com"
              }
            }



## Користувач [/user]

### Поточний користувач [GET /user/me]
Дозволяє отримати інформацію про поточного користувача, до якого був згенерованний access_token.

+ Request
    + Headers

            Authorization: Bearer [access_token]

+ Response 200 (application/json)
    + Body

            {
                "id": 999,
                "email": "sample@exampla.com",
                "name": "Іваненко Іван Іванович",
                "last_name": "Іваненко",
                "first_name": "Іван",
                "middle_name": "Іванович",

                "type": "simple",

                ...

                "type": "student",
                "student_id": 99999,
                "group_id": 9999,
                "sex": "male",

                ...

                "type": "teacher",
                "teacher_id": 9999,
                "department_id": 99,
            }
